# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-27 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190927_1607'),
    ]

    operations = [
    ]
