# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-16 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
